---
- block:
    - name: Install Nessus Agent from repo
      package:
        name: "{{ nessus_agent_package }}"
        update_cache: yes
      when: "'.rpm' not in nessus_agent_package"

    - name: Install Nessus Agent from .rpm package
      apt: deb={{ nessus_agent_package }}
      when: "'.rpm' in nessus_agent_package"
  when: nessus_agent_install_method != "url"

- block:
    - name: Download Nessus Agent
      get_url:
        url: "{{ nessus_agent_download_url }}"
        dest: "{{ nessus_agent_temp_dir }}/NessusAgent.rpm"
        checksum: "{{ nessus_agent_file_checksum }}"

    - name: Perform Agent installation
      yum:
        name: "{{ nessus_agent_temp_dir }}/NessusAgent.rpm"
        state: present
        disable_gpg_check: yes
  when: nessus_agent_install_method == "url"
