---
- block:
    - name: Install Nessus Agent from repo
      package:
        name: "{{ nessus_agent_package }}"
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default (omit) q }}"
      when: "'.deb' not in nessus_agent_package"

    - name: Install Nessus Agent from .deb package
      apt: deb={{ nessus_agent_package }}
      when: "'.deb' in nessus_agent_package"
  when: nessus_agent_install_method != "url"

- block:
    - name: Download Nessus Agent
      get_url:
        url: "{{ nessus_agent_download_url }}"
        dest: "{{ nessus_agent_temp_dir }}/NessusAgent.deb"
        checksum: "{{ nessus_agent_file_checksum }}"

    - name: Perform Agent installation
      apt:
        deb: "{{ nessus_agent_temp_dir }}/NessusAgent.deb"
  when: nessus_agent_install_method == "url"
