---
- name: Converge
  hosts: all
  become: true
  vars:
    nessus_agent_file_checksum: "md5:bc62a7e1f5833da45d48b72f4ff8bda1"
    nessus_agent_download_url: "https://www.tenable.com/downloads/api/v1/public/pages/nessus-agents/downloads/12564/download?i_agree_to_tenable_license_agreement=true" # NessusAgent-8.2.3-es7.x86_64.rpm
    nessus_agent_rules:
      default: accept
      plugin_reject:
        - 33851
      plugin_accept:
        - 10000-40000
      reject:
        - 10.42.123.0/24
      accept:
        - 10.0.0.0/24

  roles:
    - ansible-role-tenable-agent
